version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: ./nginx.docker
        volumes:
            - ./:/var/www
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - "8075:80"
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./docker
            dockerfile: ./php-fpm.docker
        volumes:
            - ./:/var/www
    php-cli:
        build:
            context: ./docker
            dockerfile: ./php-cli.docker
        volumes:
            - ./:/var/www
        tty: true

